app1/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /polls/
    path('', views.index, name='index'),
    path('index2/', views.index2, name='index2'),
    path('chile/', views.index2, name='chile'),
    path('uruguay/', views.index2, name='uruguay'),
    path('argentina/', views.index2, name='argentina'),
    path('Navbar/', views.Navbar, name='Navbar'),
    path('Matriz_Competencia_Principal/<cargo>/<capacidad>/', views.Matriz_Competencia_Principal, name='Matriz_Competencia_Principal'),
    path('Matriz_Competencia_Principal_Individual/<cargo>/<capacidad>/', views.Matriz_Competencia_Principal_Individual, name='Matriz_Competencia_Principal_Individual'),
    path('Matriz_Competencia_Principal_Pais/<cargo>/<capacidad>/', views.Matriz_Competencia_Principal_Pais, name='Matriz_Competencia_Principal_Pais'),
    path('Matriz_Competencia_Secundaria/<cargo>/<capacidad>/', views.Matriz_Competencia_Secundaria, name='Matriz_Competencia_Secundaria'),
    path('Matriz_Competencia_Secundaria_Individual/<cargo>/<capacidad>/', views.Matriz_Competencia_Secundaria_Individual, name='Matriz_Competencia_Secundaria_Individual'),
    path('Matriz_Competencia_Secundaria_Pais/<cargo>/<capacidad>/', views.Matriz_Competencia_Secundaria_Pais, name='Matriz_Competencia_Secundaria_Pais'),
    path('Matriz_Resumen_Cargo/<cargo>/', views.Matriz_Resumen_Cargo, name='Matriz_Resumen_Cargo'),
    path('Matriz_Resumen_Cargo_Individual/<cargo>/', views.Matriz_Resumen_Cargo_Individual, name='Matriz_Resumen_Cargo_Individual'),
    path('Matriz_Resumen_Cargo_Pais/<cargo>/', views.Matriz_Resumen_Cargo_Pais, name='Matriz_Resumen_Cargo_Pais'),
    path('MercadoExterno/', views.MercadoExterno, name='MercadoExterno'),

    # ex: /polls/5/
    path('<int:collection_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:job_id>/results/', views.results, name='results'),
]

astrazenecadev/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('app1/', include('app1.urls')),
    path('admin/', admin.site.urls),
]

app1/models.py
from django.db import models


class Collection(models.Model): #id by default
    location = models.CharField(max_length=200)    #location
    source = models.CharField(max_length=1000)    #source
    role = models.CharField(max_length=200)   #role
    pub_date = models.DateTimeField('date published') #time

    def __str__(self):
        return '|   Source:     {}  |   Location:    {}     |    Role:       {}  |'.format(self.source, self.location, self.role)


class Job(models.Model): #id by default
    collection = models.ForeignKey(Collection, on_delete=models.CASCADE)
    description = models.CharField(max_length=200000)    #text

    def __str__(self):
        return '|   id:     {}  |     description: {:25s}   |'.format(self.id,  self.description)

app1/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Job, Collection
from static.app1.csv.data import Data
from .fake_data import output, amp_ideal, kam_ideal, flsm_ideal
from .mercado_externo import data_mercado
import json
#------------ PROCESO DE OUTPUT ----------------------------------------
def index_navbar():
    data = json.loads(output)
    cargos = [ 'FLSM', 'AMP', 'KAM']
    navbar = {'FLSM':[],'AMP':[],'KAM':[]}
    for cargo in cargos:
        principales = list(set([x['padre'] for x in data if (x['role'] == cargo)]))     
        aux = []
        for principal in principales:
            index = {}
            secundarias = list(set([x['nombre'] for x in data if (x['padre'] == principal and x['role'] == cargo)]))
            index['nombre']= principal
            index['list']= secundarias
            navbar[cargo].append(index)
       
    return navbar

#Revisar situacion de simbolos / en medio de los nombres
Capacidades = index_navbar()
def individuos_por_cargo():
    data = json.loads(output)
    FLSM = list(set([x['id'] for x in data if (x['role'] == 'FLSM' and x['id']!= 0)]))
    AMP = list(set([x['id'] for x in data if (x['role'] == 'AMP' and x['id']!= 0)]))
    KAM = list(set([x['id'] for x in data if (x['role'] == 'KAM' and x['id']!= 0)]))
    return {'FLSM': FLSM, 'AMP': AMP, 'KAM':KAM}

individuos = individuos_por_cargo()
#-----------------------------------------------------------
#para pasar
def index(request):
    collections = Collection.objects.all()
    context = {'collections': collections, 'Data': Data, 'Otro': output}
    return render(request, 'app1/index.html', context)

def index2(request):


    from .levels import graph_3, graph_2, graph

    amp_graph_3 = graph_3(amp_ideal, 60)
    kam_graph_3 = graph_3(kam_ideal, 120)
    flsm_graph_3 = graph_3(flsm_ideal, 30)
    amp_graph_3 = json.dumps(amp_graph_3,ensure_ascii=False)
    kam_graph_3 = json.dumps(kam_graph_3,ensure_ascii=False)
    flsm_graph_3 = json.dumps(flsm_graph_3,ensure_ascii=False)

    data_g2 = graph_2(120,60,30)
    resultado = graph(data_g2)

    Fundamental = resultado[0]
    Regular = resultado[1]
    Profesional = resultado[2]

    data_g2 = json.dumps(data_g2,ensure_ascii=False)

    context = {'capacidades':Capacidades,'AMP_3': amp_graph_3, 'KAM_3': kam_graph_3, 'FLSM_3': flsm_graph_3, 'data_g2': data_g2, 'test': 12, 'Fundamental': Fundamental, 'Regular': Regular, 'Profesional': Profesional}
    return render(request, 'app1/Informacion_General.html',context)


def MercadoExterno(request):
    # Agregar Json palabra/frecuencia general
    context = {'capacidades':Capacidades, 'Data': Data, 'Frecuencias': data_mercado}
    return render(request, 'app1/Mercado_Laboral_Externo.html',context)

def Navbar(request):
    context = {'capacidades':Capacidades, 'Data': Data}
    return render(request, 'app1/Navbar.html',context)
def Topbar(request):
    return render(request, 'app1/Topbar.html')

def Matriz_Competencia_Principal(request, capacidad,cargo):
    data = json.loads(output)
    #secundarias = list(set([x['nombre'] for x in data if (x['padre'] == capacidad)]))
    secundarias = [x['list'] for x in Capacidades[cargo] if (x['nombre'] == capacidad)][0]
    individuos_ = [str(x)for x in individuos[cargo] ]

    context = {'capacidad':capacidad,'cargo':cargo,'capacidades':Capacidades,'Data':output, 'Individuos': individuos_,'secundarias':secundarias}
    return render(request, 'app1/Matriz_Competencia_Principal.html',context)

def Matriz_Competencia_Principal_Individual(request, capacidad,cargo):
    individuos_ = [str(x)for x in individuos[cargo] ]
    data = json.loads(output)
    #secundarias = list(set([x['nombre'] for x in data if (x['padre'] == capacidad)]))
    secundarias = [x['list'] for x in Capacidades[cargo] if (x['nombre'] == capacidad)][0]
     #POST id
    if request.method == "POST":
        id = request.POST['drop1']

    else:
       id = 0
    context = {'capacidad':capacidad,'cargo':cargo,'capacidades':Capacidades,'Data': output, 'id':id, 'Individuos': individuos_,'secundarias':secundarias }
    return render(request, 'app1/Matriz_Competencia_Principal_Individual.html',context)

def Matriz_Competencia_Principal_Pais(request, capacidad,cargo):
    individuos_ = [str(x)for x in individuos[cargo] ]
    data = json.loads(output)
    #secundarias = list(set([x['nombre'] for x in data if (x['padre'] == capacidad)]))
    secundarias = [x['list'] for x in Capacidades[cargo] if (x['nombre'] == capacidad)][0]
     #POST id
    if request.method == "POST":
        pais = request.POST['drop1']

    else:
       pais = 'Argentina'
    context = {'capacidad':capacidad,'cargo':cargo,'capacidades':Capacidades,'Data': output, 'Pais':pais, 'Individuos':individuos_,'secundarias':secundarias }
    return render(request, 'app1/Matriz_Competencia_Principal_Pais.html',context)

def Matriz_Competencia_Secundaria(request, capacidad,cargo):
    data = json.loads(output)
    comportamientos = [x['comportamientos'][0]['list'] for x in data if (x['nombre'] == capacidad and x['id']== 0 and x['nivel']== 'Fundamental')]
    if (not comportamientos):
        comportamientos = [['No se ha encontrado información']]
    individuos_ = [str(x)for x in individuos[cargo] ]
    context = {'capacidad':capacidad,'cargo':cargo,'capacidades':Capacidades, 'Data': output, 'Individuos': individuos_, 'comportamientos':comportamientos[0]}
    return render(request, 'app1/Matriz_Competencia_Secundaria.html',context)

def Matriz_Competencia_Secundaria_Individual(request, capacidad,cargo): #POST id
    individuos_ = [str(x)for x in individuos[cargo] ]
    data = json.loads(output)
    comportamientos = [x['comportamientos'][0]['list'] for x in data if (x['nombre'] == capacidad and x['id']== 0 and x['nivel']== 'Fundamental')]
    if request.method == "POST":
        id = request.POST['drop1']

    else:
       id = 0

    context = {'capacidad':capacidad,'cargo':cargo,'capacidades':Capacidades, 'Data': output, 'id':id, 'Individuos': individuos_,  'comportamientos':comportamientos[0]}
    return render(request, 'app1/Matriz_Competencia_Secundaria_Individual.html',context)

def Matriz_Competencia_Secundaria_Pais(request, capacidad,cargo): #POST id
    individuos_ = [str(x)for x in individuos[cargo] ]
    data = json.loads(output)
    comportamientos = [x['comportamientos'][0]['list'] for x in data if (x['nombre'] == capacidad and x['id']== 0 and x['nivel']== 'Fundamental')]
    if request.method == "POST":
        pais = request.POST['drop1']

    else:
       pais = 0

    context = {'capacidad':capacidad,'cargo':cargo,'capacidades':Capacidades, 'Data': output, 'Pais':pais, 'Individuos': individuos_,  'comportamientos':comportamientos[0]}
    return render(request, 'app1/Matriz_Competencia_Secundaria_Pais.html',context)


def Matriz_Resumen_Cargo(request, cargo):
    from .levels import random_graph_radar
    
    individuos_ = [str(x)for x in individuos[cargo] ]
    lista = [x['nombre'] for x in Capacidades[cargo]]
    data_random = random_graph_radar(lista)
    context = {'cargo': cargo, 'capacidades':Capacidades, 'Data': output, 'Individuos': individuos_, 'list': lista, 'principales': data_random}
    return render(request, 'app1/Matriz_Resumen_Cargo.html', context)

def Matriz_Resumen_Cargo_Individual(request, cargo):

    from .levels import random_graph_radar
    individuos_ = [str(x)for x in individuos[cargo] ]
    lista = [x['nombre'] for x in Capacidades[cargo]]
    data_random = random_graph_radar(lista)
    #POST id
    if request.method == "POST":
        id = request.POST['drop1']

    else:
       id = 0

    #---------------
    context = {'cargo': cargo, 'capacidades':Capacidades, 'Data': output, 'id':id, 'Individuos': individuos_, 'list': lista, 'principales':data_random}
    return render(request, 'app1/Matriz_Resumen_Cargo_Individual.html', context)

def Matriz_Resumen_Cargo_Pais(request, cargo):
    from .levels import random_graph_radar
    individuos_ = [str(x)for x in individuos[cargo] ]
    lista = [x['nombre'] for x in Capacidades[cargo]]
    data_random = random_graph_radar(lista)
    #POST id
    if request.method == "POST":
        pais = request.POST['drop1']

    else:
       id = 0

    context = {'cargo': cargo, 'capacidades':Capacidades, 'Data': output, 'Pais':pais, 'Individuos': individuos_, 'list': lista, 'principales': data_random}
    return render(request, 'app1/Matriz_Resumen_Cargo_Pais.html', context)



def detail(request, collection_id):

    #try:
    #    collection = Collection.objects.get(pk=collection_id)

    #except Collection.DoesNotExist:
    #    raise Http404("Collection does not exist")

    collection = get_object_or_404(Collection, pk=collection_id)

    return render(request, 'app1/detail.html', {'collection': collection})

def results(request, job_id):
    response = "You're looking at the results of Job %s."
    return HttpResponse(response % job_id)

app1/templates/app1/MatrizIdeal.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">

    <title>AstraZeneca - Dashboard</title>

    <!-- Custom fonts for this template-->
    <link href="{% static "app1/vendor/fontawesome-free/css/all.min.css" %}"  rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->

    <link href="{% static "app1/css/sb-admin-2.min.css" %}"  rel="stylesheet">
    <script src="https://www.gstatic.com/charts/loader.js"></script>


</head>
<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        {% include "app1/Navbar.html" %}

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">
                {% include "app1/Topbar.html" %}
                

                <!-- Capacidad 2: Comportamientos por nivel de experticia  -->
               

                <div class="container-fluid">
                    <input type="text" id="capacidad" style="display: none" value="{{ capacidad|safe }}">
                    <!-- Area Chart -->
                    <div class="col-xl-10 col-lg-10">
                       <div class="card shadow mb-10">
                        <div
                            class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                        
                             <h6 class="m-0 font-weight-bold text-primary">{{capacidad}} : Score de Nivel real vs niveles de experticia </h6>
                        </div>

                           <!-- Card Body -->
                           <div class="card-body" style="padding-bottom: 250px;">
                               <div class="chart-area">
                                   <div id="chart_div2" style="text-align: -webkit-center;" ></div>

                               </div>
                            <!-- Color System -->
                            <div class="row">
                                <div class="col-lg-6 mb-4">
                                    <div class="card bg-primary text-white shadow">
                                        <div class="card-body">
                                            comportamiento 1
                                            <div class="text-white-50 small">#4e73df</div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-6 mb-4">
                                    <div class="card bg-warning text-white shadow">
                                        <div class="card-body">
                                            comportamiento 3
                                            <div class="text-white-50 small">#f6c23e</div>
                                        </div>
                                    </div>
                                </div>
                               
                                <div class="col-lg-6 mb-4">
                                    <div class="card bg-danger text-white shadow">
                                        <div class="card-body">
                                            comportamiento 2
                                            <div class="text-white-50 small">#e74a3b</div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-6 mb-4">
                                    <div class="card bg-success text-white shadow">
                                        <div class="card-body">
                                            comportamiento 4
                                            <div class="text-white-50 small">#1cc88a</div>
                                        </div>
                                    </div>
                                </div>
                                
                                
                               
                                
                           
                            </div>
                           </div>

                           </div>
                           <!-- /.container-fluid -->
                       </div>
                   </div>

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2020</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static "app1/vendor/jquery/jquery.min.js" %}"></script>
    <script src="{% static "app1/vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static "app1/vendor/jquery-easing/jquery.easing.min.js" %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static "app1/js/sb-admin-2.min.js" %}"></script>

    <!-- Page level plugins -->
    <script src="{% static "app1/vendor/chart.js/Chart.min.js" %}"></script>

    <!-- Page level custom scripts -->
    <!-- <script src="{% static "app1/js/demo/chart-pie-demo.js" %}"></script>
    <script src="{% static "app1/js/demo/chart-area-demo.js" %}"></script>
    <script src="{% static "app1/js/demo/geograph.js" %}"></script> -->
    <script>
        var capacidad_secuntaria = "{{capacidad}}";
    </script>
    <script src="{% static "app1/js/demo/bargraph.js" %}"></script>
    <script src="{% static "app1/js/demo/geograph.js" %}"></script>
    <script src="{% static "app1/js/demo/combochart.js" %}"></script>
    
    </script>

</body>

</html>

app1/templates/app1/Matriz_Competencia_Principal.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">

    <title>AstraZeneca - Dashboard</title>

    <!-- Custom fonts for this template-->
    <link href="{% static "app1/vendor/fontawesome-free/css/all.min.css" %}"  rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->

    <link href="{% static "app1/css/sb-admin-2.min.css" %}"  rel="stylesheet">
    <script src="https://www.gstatic.com/charts/loader.js"></script>


</head>
<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        {% include "app1/Navbar.html" %}

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">
                {% include "app1/Topbar.html" %}


                <!-- Capacidad 2: Comportamientos por nivel de experticia  -->


                <div class="container-fluid">
                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">{{ capacidad}}</h1>
                    </div>
                    <input type="text/javascript" id="cargo" style="display: none" value="{{ cargo|escapejs }}">
                    <input type="text" id="capacidad" style="display: none" value="{{ capacidad|safe }}">
                    <input type="text/javascript" id="data" style="display: none" value="{{ Data|escapejs }}">

                    <!-- Area Chart -->
                    <div class="col-xl-10 col-lg-10">
                       <div class="card shadow mb-10">
                        <div
                            class="card-header py-3 d-flex flex-row align-items-center ">
                            <span class="label warning">
                                <h6 id='categoria' >   </h6>
                            </span>
                        </div>
                        <div
                            class="card-header py-3 d-flex flex-row align-items-center justify-content-between">

                             <h6 class="m-0 font-weight-bold text-primary">Nivel real respecto a categorias de experticia </h6>
                        </div>

                           <!-- Card Body -->
                           <div class="card-body" style=" height: 100%;">
                               <div class="chart-area">
                                   <div id="chart_div2" style="text-align: -webkit-center; height: 100%; width:100%;" ></div>

                               </div>
                            <!-- Grid Responsive -->
                            <div
                            style='margin-top: 50px;'
                            class="card-header py-3 d-flex flex-row align-items-center justify-content-between">

                            <h6 class="m-0 font-weight-bold text-primary">Lista de Competencias Secundarias </h6>
                           </div>
                           <div class="cards" >
                               
                               {% for cap in secundarias %}
                               <a href="{% url 'Matriz_Competencia_Secundaria' capacidad=cap cargo=cargo%}">
                               <div class="card_grid" >
                                
                                {{cap}}

                               </div>
                                </a>
                               {% endfor %}

                           </div>

                           </div>

                           </div>
                           <!-- /.container-fluid -->
                           <!-- Approach -->
                           <div class="card shadow mb-4">
                            <div class="card-header py-3">
                                <h6 class="m-0 font-weight-bold text-primary"> Resultados por Individuo</h6>
                            </div>
                            <div class="card-body">
                                    <form method = "post" action ="{% url 'Matriz_Competencia_Principal_Individual' capacidad=capacidad cargo='FLSM'%}">
                                        {% csrf_token %}
                                        <select name = "drop1" >
                                        {% for individuo in Individuos %}
                                           
                                                <option value= {{individuo}} > {{individuo}}</option>
                                           
                                        {% endfor %}
                                        </select>
                                       
                                        <input  type = "submit" value="Enviar">
                                        </form>
                            </div>
                            <!-- Pais -->
                            <div class="card-header py-3">
                                <h6 class="m-0 font-weight-bold text-primary"> Resultados por Pais</h6>
                            </div>
                            <div class="card-body">
                                    <form method = "post" action ="{% url 'Matriz_Competencia_Principal_Pais' capacidad=capacidad cargo='FLSM'%}">
                                        {% csrf_token %}
                                        <select name = "drop1" >
                                            <option value= 'Argentina' > Argentina</option>
                                            <option value= 'Chile' > Chile </option>
                                            <option value= 'Uruguay' > Uruguay </option>
                                 
                                        </select>
                                       
                                        <input  type = "submit" value="Enviar">
                                        </form>
                            </div>
                       </div>
                   </div>

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2020</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static "app1/vendor/jquery/jquery.min.js" %}"></script>
    <script src="{% static "app1/vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static "app1/vendor/jquery-easing/jquery.easing.min.js" %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static "app1/js/sb-admin-2.min.js" %}"></script>

    <!-- Page level plugins -->
    <script src="{% static "app1/vendor/chart.js/Chart.min.js" %}"></script>

    <!-- Page level custom scripts -->
    <script>
        var capacidad_secuntaria = "{{capacidad}}";
    </script>
    

    <script src="{% static "app1/js/demo/Grafico_barras_principal.js" %}"></script>

    </script>
    <style>
        .a {
            color: white;
            
        }
        .a:link {
            color: white;
            }
        .label {
            color: white;
            padding: 8px;
            }
            .warning {background-color: #e9a848;} /* Orange */
        .card_grid {
            background-color: rgb(54, 162, 235);
            color: white;
            padding: 1rem;
            height: 4rem;
        }
        .cards {
            max-width: 1200px;
            margin: 0 auto;
            display: grid;
            grid-gap: 1rem;
            margin-left: 5%;
            margin-right: 5%;
            margin-top: 50px;
            margin-bottom: 50px;
            }
        @media (min-width: 600px) {
  .cards { grid-template-columns: repeat(2, 1fr); }
}
    </style>

</body>

</html>

app1/templates/app1/detail.html
<h1>{{ collection.id }}</h1>
<ul>
{% for job in collection.job_set.all %}
    <li>{{ job.id }}</li>
    <li>{{ job.description }}</li>
{% endfor %}
</ul>